task:
  name: MomentumContrastiveTask
  params:
    backbone_name: resnet50
    backbone_params:
      in_chans: &num_channels 3
      pretrained: true
    head_name: MLPHead
    head_params:
      hidden_features: [ 512 ]
      out_features: 512
      num_layers: 2
      act_name: 'relu'
      has_norm: true
      normalize: true
    queue_size: 96000
    momentum: 0.999
    temperature: 0.07
    input_size: [*num_channels, &height 256, &width 256]

loss:
  loss_list:
  - name: CrossEntropyLoss
    params:
      target_fields:
        target: target
        input: prediction

optimizers:
  name: SGD
  params:
    lr: &initial_lr 0.03
    momentum: 0.9
    weight_decay: 0.0001

schedulers:
  name: OneCycleLR
  params:
    epochs: 100
    steps_per_epoch: 7306
    max_lr: *initial_lr
    pct_start: 0.3
  aux_params:
    interval: 'step'

data:
  common_params:
    data_folder: "${SM_CHANNEL_TRAINING}"


  train_params:
    name: ContrastiveDataset
    dataloader_params: &dataloader_params
      batch_size: 32
      num_workers: 8
      shuffle: true
      drop_last: false
    params:
      path_to_datalist: "train.csv"
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
      - &totensor
        name: ToTensorV2

    augment:
      - name: RandomResizedCrop
        params:
          height: *height
          width: *width
          scale: [0.6, 1.]

      - name: ColorJitter
        params:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
          p: 0.8
      - name: ToGray
        params:
          p: 0.2

      - name: GaussianBlur
        params:
          p: 0.5
      - name: HorizontalFlip

  valid_params:
    name: ContrastiveDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: "valid.csv"
    transform:
      - &resize
        name: Resize
        params:
          height: *height
          width: *width
      - *normalize
      - *totensor

trainer:
  gpus: 1
  max_epochs: 100
#  limit_train_batches: 10
  limit_val_batches: 0
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  precision: 32
  reload_dataloaders_every_epoch: false

experiment_name: &experiment_name test #for example: test-your_name
log_dir: '${SM_OUTPUT_DATA_DIR}/logs'

logger:
#  logger: tensorboard
  logger: mlflow
  experiment_name: *experiment_name
  tags:
    mlflow.runName: "moco" #name of the model and its hyperparams
  save_dir: "s3://test/mlruns"
  secrets_manager:
    region: "eu-west-1"
    mlflow_secret: "acme/mlflow"

checkpoint:
  monitor: train/loss
  save_last: true
  mode: min
  save_top_k: 10

profiler:
  name: 'simple'
  save_profile: false