task:
  name: SimCLR
  params:
    backbone_name: resnet50
    backbone_params:
      pretrained: true
      in_chans: 3
    pooling_name: Pooling
    head_name: MLPHead
    head_params:
      hidden_features: [512, 512]
      out_features: 512
      num_layers: 3
      act_name: 'relu'
      has_norm: true
      normalize: true
    label_size: 1234
    input_size: [3, &height 224, &width 224]

loss:
  loss_list:
  - name: NT_Xent
    params:
      temperature: 0.1
      target_fields:
        emb1 : emb1
        emb2 : emb2

optimizers:
  name: SGD
  params:
    lr: 0.001
    weight_decay: 0.0001
    momentum: 0.9
    nesterov: true

schedulers:
  name: OneCycleLR
  params:
    max_lr: 0.08 # should be 0.1 * sqrt(batch_size) if trained with very big batch size
    total_steps: 168750
    pct_start: 0.1
    anneal_strategy: 'cos'
    div_factor: 25
    final_div_factor: 10000
  aux_params:
    interval: 'step'

data:
  common_params:
    data_folder: "${SM_CHANNEL_TRAINING}"


  train_params:
    name: ContrastiveDataset
    dataloader_params: &dataloader_params
      num_workers: 8
      batch_size: 64
      drop_last: true
    params:
      path_to_datalist: 'train.csv'
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      - &totensor
        name: ToTensorV2

    augment:
      - name: RandomResizedCrop
        params:
          height: *height
          width: *width
          scale: [0.08, 1.]
          ratio: [0.75, 1.33]
      - name: HorizontalFlip
      - name: ColorJitter
        params:
          brightness: 0.8
          contrast: 0.8
          saturation: 0.8
          hue: 0.2
          p: 0.8
      - name: ToGray
        params:
          p: 0.2
      - name: GaussianBlur
        params:
          blur_limit: [7, 15]
          sigma_limit: [0.1, 2.0]

  valid_params:
    name: ContrastiveDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: 'valid.csv'
    transform:
      - &resize
        name: Resize
        params:
          height: *height
          width: *width
      - *normalize
      - *totensor

trainer:
  gpus: 1
  auto_select_gpu: true
  max_epochs: 15
#  limit_train_batches: 10
  limit_val_batches: 0
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  accelerator: dp
  precision: 32

experiment_name: &experiment_name test
log_dir: '${SM_OUTPUT_DATA_DIR}/logs'

logger:
#  logger: tensorboard
  logger: mlflow
  experiment_name: *experiment_name
  save_dir: "s3://test/mlruns"
  tags:
    mlflow.runName: "simclr_resnet50_512d"
  secrets_manager:
    region: "eu-west-1"
    mlflow_secret: "acme/mlflow"

checkpoint:
  monitor: train/loss
  save_last: true
  mode: min
  save_top_k: 1

metrics: []
